Update jwt.go
traefik-plugins/traefik-jwt-plugin pull request #70
Opened 2024-05-22 15:16 UTC by acy-norman

support for any type of JSON as request body to send to OPA (including arrays)

see also:
https://github.com/traefik-plugins/traefik-jwt-plugin/issues/54

2024-05-22 15:42 UTC, eshepelyuk requested changes
Please provide test(s) for this functonality.

2024-05-23 10:01 UTC, eshepelyuk requested changes
1. commit messages should comply to https://www.conventionalcommits.org/en/v1.0.0/
1. plz rebase and squash into single commit.

2024-05-23 13:44 UTC, acy-norman commented
done

2024-05-23 13:47 UTC, eshepelyuk reviewed
As soon as build goes green - i am ready to merge

2024-05-23 13:49 UTC, eshepelyuk requested changes
Also plz adjust commit message according to https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

to autoclose the original issue

2024-05-23 14:19 UTC, acy-norman commented
done

2024-05-23 15:34 UTC, acy-norman commented
Any idea what the issue is with this build? locally the tests work fine

2024-05-23 15:35 UTC, eshepelyuk commented
> Any idea what the issue is with this build? locally the tests work fine

maybe your local versions of linters and golang are not corresponding to CI ?

2024-05-23 15:37 UTC, acy-norman commented
and where can I get the CI settings to use them locally?

2024-05-23 15:38 UTC, eshepelyuk commented
Pipeline definition
https://github.com/traefik-plugins/workflows/blob/main/.github/workflows/build.yaml

2024-05-24 14:22 UTC, acy-norman commented
At least build worked now in my fork:

https://github.com/acy-norman/traefik-jwt-plugin/actions/runs/9225266144/job/25382399859

2024-05-24 14:26 UTC, eshepelyuk approved these changes

2024-05-24 14:26 UTC, merged

2024-05-24 14:27 UTC, eshepelyuk commented
Thanks, available in https://github.com/traefik-plugins/traefik-jwt-plugin/releases/tag/v0.8.2